We perform equal weights + risk parity + CVaR approaches to test strength of these strategies during dynamic market conditions. We test for both generic market conditions as well as (very) volatile downturns.

The goal is to minimize tail risk whilst attempting to minimize the impact on general returns / sharpe ratio.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import plotly.graph_objects as go
from scipy.stats import multivariate_normal, norm

snp = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "snp500.csv", index_col=1)
china = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "china_transformed.csv", index_col=1).reset_index()
em = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "emerging_markets.csv", index_col=1)
gold = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "gold.csv", index_col=1)
india = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "india.csv", index_col=1)
mscieurope = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "msci_europe.csv", index_col=1)
smallcapeurope = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "small_cap_europe.csv", index_col=1)

labels = ["snp", "china", "em", "gold", "india", "mscieurope", "smallcapeurope"]
dfs = [snp, china, em, gold, india, mscieurope, smallcapeurope]

def transform_date(date):
    parts = date.split(' ')
    if len(parts) == 1:
        return date
    return parts[0]

for df in dfs:
    df["Date"] = df["Date"].apply(transform_date)

china

date_sets = [set(df["Date"]) for df in dfs]

# Find the intersection of all date sets
common_dates = set.intersection(*date_sets)

# Filter each DataFrame to include only common dates
filtered_dfs = [df[df["Date"].isin(common_dates)] for df in dfs]

#for df in dfs:
#    df["Date"] = df["Date"].apply(pd.to_datetime)

#print(filtered_dfs[0].iloc[0:90]["Date"].values)

In [2]:

N = len(filtered_dfs)
T = len(filtered_dfs[0]) - 1

returns_all = np.empty((T, N))
sorted_returns_all = np.empty((T, N))
for i, df in enumerate(filtered_dfs):
    returns = df["Close"].pct_change().values[1:]
    returns_all[:, i] = returns
    sorted_returns_all[:, i] = sorted(returns)

all_dates = filtered_dfs[0]["Date"].values[1:]

In [6]:
def perform_validation(w, validation_data):
    # validation data is shape (T, N)
    
    # perform metrics
    total_return = validation_data @ w # shape (T,)
    cumulative_returns = np.cumprod(total_return + 1) - 1
    risk_free = 0.0
    std = np.std(total_return)
    downside_std = np.std(total_return[total_return > 0])
    sharpe = (255 * np.mean(total_return) - risk_free) / (np.sqrt(255) * std)
    sortino = (255 * np.mean(total_return) - risk_free) / (np.sqrt(255) * downside_std)    

    alpha = 0.10

    var_alpha = np.quantile(total_return, alpha)
    cvar = total_return[total_return <= var_alpha].mean()
    mean_return = np.mean(total_return)
    return var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return

In [7]:
import tensorflow as tf

# train weights
alpha = 0.05   # tail probability for CVaR
lambda_ = 0.5  # CVaR penalty
learning_rate = 0.01
gamma = 0.02
num_steps = 2000
beta = 0.1 # penalty volatility

def gradient(train_data, cov):

    # train data: (T,N)
    w = tf.Variable(tf.ones([N], dtype=tf.float32) / N)
    t = tf.Variable(0.0, dtype=tf.float32)  # VaR threshold

    optimizer = tf.keras.optimizers.Adam(learning_rate)

    X_tf = tf.convert_to_tensor(train_data, dtype=tf.float32) # (T,N)
    cov_tf = tf.convert_to_tensor(cov, dtype=tf.float32)  # shape (N, N)

    for step in range(num_steps):
        with tf.GradientTape() as tape:
            # enforce sum-to-1 via softmax
            w_normalized = tf.nn.softmax(w)
            w_col = tf.reshape(w_normalized, [N, 1])  # shape (N,1)

            # portfolio returns
            portfolio_returns = tf.matmul(X_tf, tf.reshape(w_col, [-1,1])) # (T)
            losses = -portfolio_returns
            cvar = t + (1 / (1 - alpha)) * tf.reduce_mean(tf.nn.relu(losses - t))
            
            # portfolio variance
            portfolio_variance = tf.squeeze(tf.transpose(w_col) @ cov_tf @ w_col)

            objective = (
                -(tf.reduce_mean(portfolio_returns) - lambda_ * cvar)
                + beta * portfolio_variance
            )

        # compute gradients
        grads = tape.gradient(objective, [w, t])
        optimizer.apply_gradients(zip(grads, [w, t]))

        if step % 200 == 0:
            print(f"Step {step}: objective = {-objective.numpy():.6f}")

    # after the optimization loop
    optimal_w = tf.nn.softmax(w).numpy()
    return optimal_w
    
def gradient_risk_parity(cov):

    # train data: (T,N)
    w = tf.Variable(tf.ones([N], dtype=tf.float32) / N)

    optimizer = tf.keras.optimizers.Adam(learning_rate)
    cov_tf = tf.convert_to_tensor(cov, dtype=tf.float32)  # shape (N, N)

    for step in range(num_steps):
        with tf.GradientTape() as tape:
            # enforce sum-to-1 via softmax
            w_normalized = tf.nn.softmax(w)
            w_col = tf.reshape(w_normalized, [N, 1])  # shape (N,1)
            
            # portfolio variance
            portfolio_variance = tf.squeeze(tf.transpose(w_col) @ cov_tf @ w_col)

            marginal = cov_tf @ w_col
            risk_contrib = w_col * marginal

            risk_parity_target = portfolio_variance / N
            objective = tf.reduce_sum((risk_contrib - risk_parity_target)**2) + gamma*tf.reduce_sum(tf.math.square(w_col))

        # compute gradients
        grads = tape.gradient(objective, [w])
        optimizer.apply_gradients(zip(grads, [w]))

        if step % 200 == 0:
            print(f"Step {step}: objective = {-objective.numpy():.6f}")

    # after the optimization loop
    optimal_w = tf.nn.softmax(w).numpy()
    return optimal_w

def gradient_reduced(train_data, cov):

    # train data: (T,N)
    w = tf.Variable(tf.ones([N], dtype=tf.float32) / N)
    t = tf.Variable(0.0, dtype=tf.float32)  # VaR threshold

    optimizer = tf.keras.optimizers.Adam(learning_rate)

    X_tf = tf.convert_to_tensor(train_data, dtype=tf.float32) # (T,N)
    cov_tf = tf.convert_to_tensor(cov, dtype=tf.float32)  # shape (N, N)

    for step in range(num_steps):
        with tf.GradientTape() as tape:
            # enforce sum-to-1 via softmax
            w_normalized = tf.nn.softmax(w)
            w_col = tf.reshape(w_normalized, [N, 1])  # shape (N,1)

            # portfolio returns
            portfolio_returns = tf.matmul(X_tf, tf.reshape(w_col, [-1,1])) # (T)
            losses = -portfolio_returns
            cvar = t + (1 / (1 - alpha)) * tf.reduce_mean(tf.nn.relu(losses - t))

            objective = -(tf.reduce_mean(portfolio_returns) - lambda_ * cvar) + gamma*tf.reduce_sum(tf.math.square(w_col))

        # compute gradients
        grads = tape.gradient(objective, [w, t])
        optimizer.apply_gradients(zip(grads, [w, t]))

        if step % 200 == 0:
            print(f"Step {step}: objective = {-objective.numpy():.6f}")

    # after the optimization loop
    optimal_w = tf.nn.softmax(w).numpy()
    return optimal_w

In [8]:
# run

def select_random_block(returns, block_size):
    n = len(returns)
    lst = list(range(n))
    chosen_idx = np.random.choice(lst)
    while not (block_size < chosen_idx < n - block_size):
        chosen_idx = np.random.choice(n)
    selected_train_data = returns[chosen_idx - block_size : chosen_idx]
    selected_validation_data = returns[chosen_idx : chosen_idx + block_size]
    return selected_train_data, selected_validation_data

def block_bootstrap(n_bootstrap, returns_all):

    sharpes_w_opt= []
    sharpes_w_rp = []
    sharpes_w_eqw = []

    mean_return_w_opt = []
    mean_return_w_rp = []
    mean_return_w_eqw = []

    sortinos_w_opt = []
    sortinos_w_rp = []
    sortinos_w_eqw = []

    vars_w_opt = []
    vars_w_rp = []
    vars_w_eqw = []

    cvars_w_opt = []
    cvars_w_rp = []
    cvars_w_eqw = []

    for _ in range(n_bootstrap):
        train_data, val_data = select_random_block(returns_all, 252)
        cov = np.cov(train_data, rowvar=False)

        w_opt = gradient(train_data, cov)
        w_rp = gradient_risk_parity(cov)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_opt, val_data)

        sharpes_w_opt.append(sharpe)
        sortinos_w_opt.append(sortino)
        vars_w_opt.append(var_alpha)
        cvars_w_opt.append(cvar)
        mean_return_w_opt.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_rp, val_data)

        sharpes_w_rp.append(sharpe)
        sortinos_w_rp.append(sortino)
        vars_w_rp.append(var_alpha)
        cvars_w_rp.append(cvar)
        mean_return_w_rp.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(np.ones(N) / N, val_data)

        sharpes_w_eqw.append(sharpe)
        sortinos_w_eqw.append(sortino)
        vars_w_eqw.append(var_alpha)
        cvars_w_eqw.append(cvar)
        mean_return_w_eqw.append(mean_return)

    df = pd.DataFrame({
        "Sharpes": [np.mean(sharpes_w_eqw), np.mean(sharpes_w_rp), np.mean(sharpes_w_opt)],
        "Sortinos": [np.mean(sortinos_w_eqw), np.mean(sortinos_w_rp), np.mean(sortinos_w_opt)],
        "Vars": [np.mean(vars_w_eqw), np.mean(vars_w_rp), np.mean(vars_w_opt)],
        "Cvars": [np.mean(cvars_w_eqw), np.mean(cvars_w_rp), np.mean(cvars_w_opt)],
        "MeanReturn": [np.mean(mean_return_w_eqw), np.mean(mean_return_w_rp), np.mean(mean_return_w_opt)],
    }, index=["Equal weights", "Risk parity", "Return + CVaR"])

    return df

def rolling_window(window_size, stepsize, validation_size, data):
    # data is (T,N)

    sharpes_w_opt= []
    sharpes_w_rp = []
    sharpes_w_eqw = []

    mean_return_w_opt = []
    mean_return_w_rp = []
    mean_return_w_eqw = []

    sortinos_w_opt = []
    sortinos_w_rp = []
    sortinos_w_eqw = []

    vars_w_opt = []
    vars_w_rp = []
    vars_w_eqw = []

    cvars_w_opt = []
    cvars_w_rp = []
    cvars_w_eqw = []
    T, N = data.shape
    weights_opt = []
    weights_rp = []
    for idx in range(0, T - window_size - validation_size, stepsize):
        train_data = data[idx:idx+window_size]
        val_data = data[idx+window_size:idx+window_size+validation_size]
        cov = np.cov(train_data, rowvar=False)

        w_opt = gradient_reduced(train_data, cov)
        w_rp = gradient_risk_parity(cov)

        print('w opt:', w_opt)
        print('w rp:', w_rp)

        weights_opt.append(w_opt)
        weights_rp.append(w_rp)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_opt, val_data)

        sharpes_w_opt.append(sharpe)
        sortinos_w_opt.append(sortino)
        vars_w_opt.append(var_alpha)
        cvars_w_opt.append(cvar)
        mean_return_w_opt.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(w_rp, val_data)

        sharpes_w_rp.append(sharpe)
        sortinos_w_rp.append(sortino)
        vars_w_rp.append(var_alpha)
        cvars_w_rp.append(cvar)
        mean_return_w_rp.append(mean_return)

        (
            var_alpha, cvar, sharpe, sortino, cumulative_returns, mean_return
        ) = perform_validation(np.ones(N) / N, val_data)

        sharpes_w_eqw.append(sharpe)
        sortinos_w_eqw.append(sortino)
        vars_w_eqw.append(var_alpha)
        cvars_w_eqw.append(cvar)
        mean_return_w_eqw.append(mean_return)

    df = pd.DataFrame({
        "Sharpes": [np.mean(sharpes_w_eqw), np.mean(sharpes_w_rp), np.mean(sharpes_w_opt)],
        "Sortinos": [np.mean(sortinos_w_eqw), np.mean(sortinos_w_rp), np.mean(sortinos_w_opt)],
        "Vars": [np.mean(vars_w_eqw), np.mean(vars_w_rp), np.mean(vars_w_opt)],
        "Cvars": [np.mean(cvars_w_eqw), np.mean(cvars_w_rp), np.mean(cvars_w_opt)],
        "MeanReturn": [np.mean(mean_return_w_eqw), np.mean(mean_return_w_rp), np.mean(mean_return_w_opt)],
    }, index=["Equal weights", "Risk parity", "Return + CVaR"])

    weights_opt = np.array(weights_opt)
    weights_rp = np.array(weights_rp)

    print(weights_opt.shape)

    return df, np.mean(weights_opt, axis=0), np.mean(weights_rp, axis=0)

In [9]:
df, weights_opt, weights_rp = rolling_window(
    window_size=252*2,
    stepsize=30,
    validation_size=252,
    data=returns_all
)
df

print('mean weights optimized:', weights_opt)
print('mean weights risk parity:', weights_rp)

Step 0: objective = -0.004332
Step 200: objective = -0.003232
Step 400: objective = -0.003232
Step 600: objective = -0.003232
Step 800: objective = -0.003232
Step 1000: objective = -0.003232
Step 1200: objective = -0.003232
Step 1400: objective = -0.003232
Step 1600: objective = -0.003232
Step 1800: objective = -0.003232
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15016459 0.12259774 0.14088295 0.15251325 0.13363686 0.14659537
 0.15360917]
w rp: [0.14287    0.14287175 0.14285295 0.14285785 0.14284307 0.1428522
 0.1428522 ]
Step 0: objective = -0.004238
Step 200: objective = -0.003134
Step 400: objective = -0.003134
Step 600: objective = -0.003134
Step 800: objective = -0.003134
Step 1000: objective = -0.003134
Step 1200: objective = -0.003134
Step 1400: objective = -0.003134
Step 1600: objective = -0.003134
Step 1800: objective = -0.003134
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14938746 0.11608382 0.14407052 0.14952083 0.14155515 0.14477862
 0.15460362]
w rp: [0.14287    0.14287175 0.14285295 0.14285785 0.14284307 0.1428522
 0.1428522 ]
Step 0: objective = -0.004110
Step 200: objective = -0.002997
Step 400: objective = -0.002997
Step 600: objective = -0.002997
Step 800: objective = -0.002997
Step 1000: objective = -0.002997
Step 1200: objective = -0.002997
Step 1400: objective = -0.002997
Step 1600: objective = -0.002997
Step 1800: objective = -0.002997
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14666082 0.1190551  0.1494242  0.14995031 0.1362842  0.1443996
 0.15422575]
w rp: [0.14287    0.14287175 0.14285295 0.14285785 0.14284307 0.1428522
 0.1428522 ]
Step 0: objective = -0.003885
Step 200: objective = -0.002774
Step 400: objective = -0.002774
Step 600: objective = -0.002774
Step 800: objective = -0.002774
Step 1000: objective = -0.002774
Step 1200: objective = -0.002774
Step 1400: objective = -0.002774
Step 1600: objective = -0.002774
Step 1800: objective = -0.002774
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14988296 0.11332215 0.15667666 0.14692979 0.139468   0.14198165
 0.1517388 ]
w rp: [0.14283268 0.14286028 0.14285286 0.14286028 0.1428827  0.14285563
 0.14285563]
Step 0: objective = -0.003664
Step 200: objective = -0.002612
Step 400: objective = -0.002612
Step 600: objective = -0.002612
Step 800: objective = -0.002612
Step 1000: objective = -0.002612
Step 1200: objective = -0.002612
Step 1400: objective = -0.002612
Step 1600: objective = -0.002612
Step 1800: objective = -0.002612
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14910309 0.11406577 0.1566053  0.14458674 0.13852881 0.1447504
 0.15235986]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285713 0.14285715
 0.14285715]
Step 0: objective = -0.003658
Step 200: objective = -0.002599
Step 400: objective = -0.002599
Step 600: objective = -0.002599
Step 800: objective = -0.002599
Step 1000: objective = -0.002599
Step 1200: objective = -0.002599
Step 1400: objective = -0.002599
Step 1600: objective = -0.002599
Step 1800: objective = -0.002599
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14110425 0.12644026 0.15943885 0.14404264 0.13650863 0.1446763
 0.14778908]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285713 0.14285715
 0.14285715]
Step 0: objective = -0.003626
Step 200: objective = -0.002556
Step 400: objective = -0.002556
Step 600: objective = -0.002556
Step 800: objective = -0.002556
Step 1000: objective = -0.002557
Step 1200: objective = -0.002557
Step 1400: objective = -0.002556
Step 1600: objective = -0.002556
Step 1800: objective = -0.002556
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14063576 0.12710467 0.1603528  0.14394172 0.13538122 0.146025
 0.14655876]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285713 0.14285715
 0.14285715]
Step 0: objective = -0.003323
Step 200: objective = -0.002285
Step 400: objective = -0.002285
Step 600: objective = -0.002285
Step 800: objective = -0.002285
Step 1000: objective = -0.002285
Step 1200: objective = -0.002286
Step 1400: objective = -0.002285
Step 1600: objective = -0.002285
Step 1800: objective = -0.002285
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14873691 0.12738992 0.15577996 0.1318649  0.14119789 0.14315662
 0.15187377]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003481
Step 200: objective = -0.002504
Step 400: objective = -0.002504
Step 600: objective = -0.002504
Step 800: objective = -0.002504
Step 1000: objective = -0.002504
Step 1200: objective = -0.002504
Step 1400: objective = -0.002504
Step 1600: objective = -0.002504
Step 1800: objective = -0.002504
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15136366 0.1343471  0.14697464 0.13220243 0.14232542 0.1426683
 0.15011846]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003433
Step 200: objective = -0.002456
Step 400: objective = -0.002456
Step 600: objective = -0.002456
Step 800: objective = -0.002456
Step 1000: objective = -0.002456
Step 1200: objective = -0.002456
Step 1400: objective = -0.002456
Step 1600: objective = -0.002456
Step 1800: objective = -0.002456
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15442502 0.13530846 0.14801353 0.12761326 0.14482936 0.14145923
 0.14835118]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003530
Step 200: objective = -0.002581
Step 400: objective = -0.002582
Step 600: objective = -0.002581
Step 800: objective = -0.002581
Step 1000: objective = -0.002581
Step 1200: objective = -0.002582
Step 1400: objective = -0.002581
Step 1600: objective = -0.002581
Step 1800: objective = -0.002582
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15432766 0.13563395 0.14797461 0.12735897 0.13517417 0.14829482
 0.15123582]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003734
Step 200: objective = -0.002822
Step 400: objective = -0.002822
Step 600: objective = -0.002822
Step 800: objective = -0.002822
Step 1000: objective = -0.002822
Step 1200: objective = -0.002822
Step 1400: objective = -0.002822
Step 1600: objective = -0.002823
Step 1800: objective = -0.002823
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15246336 0.13780786 0.144668   0.1335004  0.13992774 0.14485995
 0.14677267]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003804
Step 200: objective = -0.002872
Step 400: objective = -0.002872
Step 600: objective = -0.002872
Step 800: objective = -0.002872
Step 1000: objective = -0.002872
Step 1200: objective = -0.002872
Step 1400: objective = -0.002873
Step 1600: objective = -0.002872
Step 1800: objective = -0.002874
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.152285   0.13083546 0.146294   0.13933732 0.14236182 0.14377916
 0.1451072 ]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003501
Step 200: objective = -0.002529
Step 400: objective = -0.002529
Step 600: objective = -0.002529
Step 800: objective = -0.002529
Step 1000: objective = -0.002529
Step 1200: objective = -0.002529
Step 1400: objective = -0.002530
Step 1600: objective = -0.002529
Step 1800: objective = -0.002529
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14976326 0.15201566 0.14321591 0.1336903  0.13600054 0.14267051
 0.14264384]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003432
Step 200: objective = -0.002441
Step 400: objective = -0.002441
Step 600: objective = -0.002441
Step 800: objective = -0.002441
Step 1000: objective = -0.002441
Step 1200: objective = -0.002441
Step 1400: objective = -0.002441
Step 1600: objective = -0.002444
Step 1800: objective = -0.002446
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14041993 0.15246125 0.14612529 0.13760947 0.14045337 0.14228155
 0.1406492 ]
w rp: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003665
Step 200: objective = -0.002699
Step 400: objective = -0.002699
Step 600: objective = -0.002699
Step 800: objective = -0.002699
Step 1000: objective = -0.002700
Step 1200: objective = -0.002700
Step 1400: objective = -0.002700
Step 1600: objective = -0.002699
Step 1800: objective = -0.002700
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14648674 0.14949389 0.13807446 0.13983078 0.14467292 0.14116018
 0.14028107]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003605
Step 200: objective = -0.002618
Step 400: objective = -0.002618
Step 600: objective = -0.002618
Step 800: objective = -0.002618
Step 1000: objective = -0.002618
Step 1200: objective = -0.002618
Step 1400: objective = -0.002618
Step 1600: objective = -0.002618
Step 1800: objective = -0.002618
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14635326 0.15583973 0.1385069  0.14324264 0.13631247 0.14138773
 0.13835733]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003722
Step 200: objective = -0.002732
Step 400: objective = -0.002732
Step 600: objective = -0.002732
Step 800: objective = -0.002732
Step 1000: objective = -0.002732
Step 1200: objective = -0.002732
Step 1400: objective = -0.002732
Step 1600: objective = -0.002732
Step 1800: objective = -0.002732
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.14950582 0.16412899 0.13162476 0.15526697 0.13335228 0.13368385
 0.13243736]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003670
Step 200: objective = -0.002657
Step 400: objective = -0.002657
Step 600: objective = -0.002657
Step 800: objective = -0.002657
Step 1000: objective = -0.002657
Step 1200: objective = -0.002657
Step 1400: objective = -0.002657
Step 1600: objective = -0.002657
Step 1800: objective = -0.002657
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15180844 0.16775957 0.12723148 0.15818593 0.13201094 0.13074191
 0.13226165]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003588
Step 200: objective = -0.002593
Step 400: objective = -0.002593
Step 600: objective = -0.002593
Step 800: objective = -0.002593
Step 1000: objective = -0.002593
Step 1200: objective = -0.002593
Step 1400: objective = -0.002593
Step 1600: objective = -0.002593
Step 1800: objective = -0.002594
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15280622 0.16414286 0.12851574 0.1524648  0.13606986 0.13266884
 0.13333163]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003555
Step 200: objective = -0.002547
Step 400: objective = -0.002547
Step 600: objective = -0.002547
Step 800: objective = -0.002547
Step 1000: objective = -0.002547
Step 1200: objective = -0.002547
Step 1400: objective = -0.002547
Step 1600: objective = -0.002547
Step 1800: objective = -0.002547
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15260743 0.16260035 0.12806657 0.15569897 0.13179268 0.13443096
 0.13480309]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.003623
Step 200: objective = -0.002606
Step 400: objective = -0.002606
Step 600: objective = -0.002606
Step 800: objective = -0.002607
Step 1000: objective = -0.002608
Step 1200: objective = -0.002607
Step 1400: objective = -0.002607
Step 1600: objective = -0.002607
Step 1800: objective = -0.002607
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15556    0.16078596 0.1243212  0.16033226 0.1334448  0.130885
 0.13467075]
w rp: [0.14285715 0.14285715 0.14285713 0.14285715 0.14285715 0.14285715
 0.14285715]
Step 0: objective = -0.004344
Step 200: objective = -0.003260
Step 400: objective = -0.003260
Step 600: objective = -0.003260
Step 800: objective = -0.003260
Step 1000: objective = -0.003260
Step 1200: objective = -0.003260
Step 1400: objective = -0.003260
Step 1600: objective = -0.003262
Step 1800: objective = -0.003260
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15482922 0.17008306 0.11952373 0.17719094 0.12297969 0.12878491
 0.12660845]
w rp: [0.14285076 0.14286317 0.14285532 0.14285469 0.1428517  0.14286217
 0.14286217]
Step 0: objective = -0.004234
Step 200: objective = -0.003039
Step 400: objective = -0.003039
Step 600: objective = -0.003039
Step 800: objective = -0.003039
Step 1000: objective = -0.003039
Step 1200: objective = -0.003039
Step 1400: objective = -0.003039
Step 1600: objective = -0.003039
Step 1800: objective = -0.003039
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
w opt: [0.15765157 0.17369539 0.12041711 0.17531626 0.12287574 0.12458072
 0.12546325]
w rp: [0.14285646 0.14285408 0.14286095 0.14285728 0.14285386 0.14286949
 0.14284794]
Step 0: objective = -0.004246
Step 200: objective = -0.003021
Step 400: objective = -0.003021
Step 600: objective = -0.003021
Step 800: objective = -0.003021
Step 1000: objective = -0.003021
Step 1200: objective = -0.003021
Step 1400: objective = -0.003021
Step 1600: objective = -0.003025
Step 1800: objective = -0.003021
Step 0: objective = -0.002857

Run once more, using entire dataset

In [11]:
training_pct = 0.7
idx = int(training_pct*T)

training_set_entire = returns_all[:idx,:]
validation_set_entire = returns_all[idx:,:]

cov = np.cov(training_set_entire, rowvar=False)
w_opt = gradient_reduced(training_set_entire, cov)
w_rp = gradient_risk_parity(cov)

(
    var_alpha, cvar, sharpe, sortino, cumulative_returns_opt, mean_return
) = perform_validation(w_opt, validation_set_entire)

print('OPTIMIZED WEIGHTS STATS')
print('var:', var_alpha)
print('cvar:', cvar)
print('sharpe:', sharpe)
print('sortino:', sortino)
print('mean return:', mean_return)

(
    var_alpha, cvar, sharpe, sortino, cumulative_returns_rp, mean_return
) = perform_validation(w_rp, training_set_entire)

print()
print('RISK PARITY STATS')
print('var:', var_alpha)
print('cvar:', cvar)
print('sharpe:', sharpe)
print('sortino:', sortino)
print('mean return:', mean_return)

(
    var_alpha, cvar, sharpe, sortino, cumulative_returns_eqw, mean_return
) = perform_validation(np.ones(N) / N, training_set_entire)

print()
print('EQUAL WEIGHTS STATS')
print('var:', var_alpha)
print('cvar:', cvar)
print('sharpe:', sharpe)
print('sortino:', sortino)
print('mean return:', mean_return)

print()
print('optimized weights:', w_opt)
print('risk parity weights:', w_rp)

fig = go.Figure()
L = list(range(len(validation_set_entire)))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_eqw, name="equal weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_opt, name="optimized weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_rp, name="risk parity weights"))
fig.show()

Step 0: objective = -0.004094
Step 200: objective = -0.002960
Step 400: objective = -0.002960
Step 600: objective = -0.002960
Step 800: objective = -0.002960
Step 1000: objective = -0.002960
Step 1200: objective = -0.002960
Step 1400: objective = -0.002960
Step 1600: objective = -0.002960
Step 1800: objective = -0.002960
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
OPTIMIZED WEIGHTS STATS
var: -0.006032235755893444
cvar: -0.010700151303303526
sharpe: 1.6171918538482555
sortino: 2.555942477348651
mean return: 0.0006213304502896785

RISK PARITY STATS
var: -0.008907919140814962
cvar: -0.01533025409237657
sharpe: 0.4342712013149262
sortino: 0.7033863189516916
mean return: 0.0002252145769865999

EQUAL WEIGHTS STATS
var: -0.00890768163633233
cvar: -0.01533108707945228
sharpe: 0.43425967801180204
sortino: 0.703369861301827
mean return: 0.00022522039067961023

optimized weights: [0.15060064 0.13204414 0.1372203  0.15536211 0.14059857 0.1403463
 0.14382796]
risk parity weights: [0.14287588 0.14288001 0.14284748 0.14288223 0.14282082 0.14284682
 0.14284682]

In [76]:
def sample(sorted_returns, amount):
    res = []
    n = len(sorted_returns)
    for _ in range(amount):
        u = np.random.uniform()
        for i,val in enumerate(sorted_returns):
            if i >= n*u:
                res.append(val)
                break
    return res

def sample_combined(sorted_returns, amount, weights):
    # weights: (N)
    # sorted returns: (T, N) array
    final = np.zeros_like(sorted_returns)
    for i in range(sorted_returns.shape[1]):
        final[:,i] = sample(sorted_returns[:,i], amount)
    
    return final @ weights

In [77]:
df = block_bootstrap(200, returns_all)
df

Step 0: objective = -0.003101
Step 200: objective = 0.000059
Step 400: objective = 0.000129
Step 600: objective = 0.000149
Step 800: objective = 0.000159
Step 1000: objective = 0.000162
Step 1200: objective = 0.000165
Step 1400: objective = 0.000162
Step 1600: objective = 0.000164
Step 1800: objective = 0.000169
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002597
Step 200: objective = 0.000866
Step 400: objective = 0.001011
Step 600: objective = 0.001039
Step 800: objective = 0.001048
Step 1000: objective = 0.001052
Step 1200: objective = 0.001058
Step 1400: objective = 0.001060
Step 1600: objective = 0.001061
Step 1800: objective = 0.001062
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002831
Step 200: objective = -0.000165
Step 400: objective = -0.000080
Step 600: objective = -0.000062
Step 800: objective = -0.000054
Step 1000: objective = -0.000049
Step 1200: objective = -0.000050
Step 1400: objective = -0.000046
Step 1600: objective = -0.000048
Step 1800: objective = -0.000051
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002028
Step 200: objective = 0.001739
Step 400: objective = 0.002003
Step 600: objective = 0.002039
Step 800: objective = 0.002053
Step 1000: objective = 0.002058
Step 1200: objective = 0.002062
Step 1400: objective = 0.002061
Step 1600: objective = 0.002065
Step 1800: objective = 0.002067
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001387
Step 200: objective = 0.001282
Step 400: objective = 0.001360
Step 600: objective = 0.001379
Step 800: objective = 0.001385
Step 1000: objective = 0.001391
Step 1200: objective = 0.001389
Step 1400: objective = 0.001394
Step 1600: objective = 0.001386
Step 1800: objective = 0.001395
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001508
Step 200: objective = 0.001723
Step 400: objective = 0.001887
Step 600: objective = 0.001912
Step 800: objective = 0.001919
Step 1000: objective = 0.001928
Step 1200: objective = 0.001918
Step 1400: objective = 0.001934
Step 1600: objective = 0.001936
Step 1800: objective = 0.001934
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003866
Step 200: objective = 0.000628
Step 400: objective = 0.000823
Step 600: objective = 0.000865
Step 800: objective = 0.000877
Step 1000: objective = 0.000889
Step 1200: objective = 0.000890
Step 1400: objective = 0.000899
Step 1600: objective = 0.000902
Step 1800: objective = 0.000901
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001551
Step 200: objective = 0.001235
Step 400: objective = 0.001359
Step 600: objective = 0.001388
Step 800: objective = 0.001399
Step 1000: objective = 0.001403
Step 1200: objective = 0.001408
Step 1400: objective = 0.001410
Step 1600: objective = 0.001411
Step 1800: objective = 0.001412
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002721
Step 200: objective = 0.000147
Step 400: objective = 0.000225
Step 600: objective = 0.000239
Step 800: objective = 0.000247
Step 1000: objective = 0.000251
Step 1200: objective = 0.000253
Step 1400: objective = 0.000252
Step 1600: objective = 0.000250
Step 1800: objective = 0.000253
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003099
Step 200: objective = -0.000025
Step 400: objective = 0.000036
Step 600: objective = 0.000052
Step 800: objective = 0.000059
Step 1000: objective = 0.000063
Step 1200: objective = 0.000065
Step 1400: objective = 0.000062
Step 1600: objective = 0.000064
Step 1800: objective = 0.000068
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002363
Step 200: objective = 0.000637
Step 400: objective = 0.000717
Step 600: objective = 0.000730
Step 800: objective = 0.000741
Step 1000: objective = 0.000744
Step 1200: objective = 0.000747
Step 1400: objective = 0.000746
Step 1600: objective = 0.000749
Step 1800: objective = 0.000750
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003171
Step 200: objective = -0.000234
Step 400: objective = -0.000185
Step 600: objective = -0.000171
Step 800: objective = -0.000165
Step 1000: objective = -0.000164
Step 1200: objective = -0.000162
Step 1400: objective = -0.000159
Step 1600: objective = -0.000158
Step 1800: objective = -0.000185
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001873
Step 200: objective = 0.001036
Step 400: objective = 0.001102
Step 600: objective = 0.001117
Step 800: objective = 0.001126
Step 1000: objective = 0.001130
Step 1200: objective = 0.001131
Step 1400: objective = 0.001131
Step 1600: objective = 0.001134
Step 1800: objective = 0.001134
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001159
Step 200: objective = 0.001482
Step 400: objective = 0.001573
Step 600: objective = 0.001593
Step 800: objective = 0.001590
Step 1000: objective = 0.001598
Step 1200: objective = 0.001602
Step 1400: objective = 0.001590
Step 1600: objective = 0.001599
Step 1800: objective = 0.001580
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001404
Step 200: objective = 0.001645
Step 400: objective = 0.001773
Step 600: objective = 0.001801
Step 800: objective = 0.001812
Step 1000: objective = 0.001818
Step 1200: objective = 0.001821
Step 1400: objective = 0.001823
Step 1600: objective = 0.001824
Step 1800: objective = 0.001810
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004354
Step 200: objective = -0.000546
Step 400: objective = -0.000474
Step 600: objective = -0.000452
Step 800: objective = -0.000444
Step 1000: objective = -0.000440
Step 1200: objective = -0.000462
Step 1400: objective = -0.000435
Step 1600: objective = -0.000438
Step 1800: objective = -0.000433
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001256
Step 200: objective = 0.001022
Step 400: objective = 0.001034
Step 600: objective = 0.001040
Step 800: objective = 0.001042
Step 1000: objective = 0.001044
Step 1200: objective = 0.001044
Step 1400: objective = 0.001045
Step 1600: objective = 0.001039
Step 1800: objective = 0.001044
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001585
Step 200: objective = 0.001572
Step 400: objective = 0.001701
Step 600: objective = 0.001732
Step 800: objective = 0.001743
Step 1000: objective = 0.001749
Step 1200: objective = 0.001752
Step 1400: objective = 0.001754
Step 1600: objective = 0.001752
Step 1800: objective = 0.001755
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002981
Step 200: objective = -0.000202
Step 400: objective = -0.000151
Step 600: objective = -0.000138
Step 800: objective = -0.000132
Step 1000: objective = -0.000130
Step 1200: objective = -0.000128
Step 1400: objective = -0.000128
Step 1600: objective = -0.000131
Step 1800: objective = -0.000125
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001364
Step 200: objective = 0.001268
Step 400: objective = 0.001331
Step 600: objective = 0.001355
Step 800: objective = 0.001358
Step 1000: objective = 0.001366
Step 1200: objective = 0.001370
Step 1400: objective = 0.001371
Step 1600: objective = 0.001371
Step 1800: objective = 0.001373
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001610
Step 200: objective = 0.001746
Step 400: objective = 0.001883
Step 600: objective = 0.001908
Step 800: objective = 0.001930
Step 1000: objective = 0.001939
Step 1200: objective = 0.001943
Step 1400: objective = 0.001945
Step 1600: objective = 0.001942
Step 1800: objective = 0.001940
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003740
Step 200: objective = 0.000476
Step 400: objective = 0.000559
Step 600: objective = 0.000572
Step 800: objective = 0.000580
Step 1000: objective = 0.000584
Step 1200: objective = 0.000586
Step 1400: objective = 0.000587
Step 1600: objective = 0.000590
Step 1800: objective = 0.000589
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001842
Step 200: objective = 0.000834
Step 400: objective = 0.000870
Step 600: objective = 0.000881
Step 800: objective = 0.000885
Step 1000: objective = 0.000888
Step 1200: objective = 0.000888
Step 1400: objective = 0.000890
Step 1600: objective = 0.000891
Step 1800: objective = 0.000890
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001594
Step 200: objective = 0.001043
Step 400: objective = 0.001174
Step 600: objective = 0.001197
Step 800: objective = 0.001206
Step 1000: objective = 0.001208
Step 1200: objective = 0.001212
Step 1400: objective = 0.001209
Step 1600: objective = 0.001213
Step 1800: objective = 0.001216
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004446
Step 200: objective = 0.000192
Step 400: objective = 0.000314
Step 600: objective = 0.000343
Step 800: objective = 0.000354
Step 1000: objective = 0.000355
Step 1200: objective = 0.000361
Step 1400: objective = 0.000365
Step 1600: objective = 0.000364
Step 1800: objective = 0.000366
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.003522
Step 200: objective = -0.000646
Step 400: objective = -0.000607
Step 600: objective = -0.000602
Step 800: objective = -0.000595
Step 1000: objective = -0.000591
Step 1200: objective = -0.000590
Step 1400: objective = -0.000595
Step 1600: objective = -0.000589
Step 1800: objective = -0.000589
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004147
Step 200: objective = 0.000083
Step 400: objective = 0.000174
Step 600: objective = 0.000196
Step 800: objective = 0.000207
Step 1000: objective = 0.000212
Step 1200: objective = 0.000216
Step 1400: objective = 0.000218
Step 1600: objective = 0.000215
Step 1800: objective = 0.000220
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004688
Step 200: objective = -0.001069
Step 400: objective = -0.000999
Step 600: objective = -0.000980
Step 800: objective = -0.000972
Step 1000: objective = -0.000971
Step 1200: objective = -0.000967
Step 1400: objective = -0.000964
Step 1600: objective = -0.000971
Step 1800: objective = -0.000962
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.002343
Step 200: objective = 0.000667
Step 400: objective = 0.000751
Step 600: objective = 0.000768
Step 800: objective = 0.000777
Step 1000: objective = 0.000780
Step 1200: objective = 0.000783
Step 1400: objective = 0.000783
Step 1600: objective = 0.000786
Step 1800: objective = 0.000773
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001715
Step 200: objective = 0.001342
Step 400: objective = 0.001580
Step 600: objective = 0.001614
Step 800: objective = 0.001626
Step 1000: objective = 0.001631
Step 1200: objective = 0.001635
Step 1400: objective = 0.001635
Step 1600: objective = 0.001637
Step 1800: objective = 0.001632
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.004109
Step 200: objective = -0.000299
Step 400: objective = -0.000283
Step 600: objective = -0.000271
Step 800: objective = -0.000266
Step 1000: objective = -0.000261
Step 1200: objective = -0.000258
Step 1400: objective = -0.000255
Step 1600: objective = -0.000256
Step 1800: objective = -0.000254
Step 0: objective = -0.000000
Step 200: objective = -0.000000
Step 400: objective = -0.000000
Step 600: objective = -0.000000
Step 800: objective = -0.000000
Step 1000: objective = -0.000000
Step 1200: objective = -0.000000
Step 1400: objective = -0.000000
Step 1600: objective = -0.000000
Step 1800: objective = -0.000000
Step 0: objective = -0.001679
Step 200: objective = 0.001351
Step 400: objective = 0.001559
Step 600: objective = 0.001588
Step 800: objective = 0.001600
Step 1000: objective = 0.001604

                Sharpes  Sortinos      Vars     Cvars  MeanReturn
Equal weights  1.051824  1.738873 -0.007703 -0.013041    0.000412
Risk parity    1.039199  1.717977 -0.007680 -0.012998    0.000405
Return + CVaR  0.583604  0.900634 -0.008890 -0.014768    0.000243

Test bear market conditions for all approaches

In [ ]:

val_returns_total = []
train_returns_total = []

for df in filtered_dfs:
    df_datetime = df.copy()
    df_datetime["Date"] = pd.to_datetime(df_datetime["Date"])
    train = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2024-01-01"))
        & (df_datetime["Date"] <= pd.to_datetime("2025-01-01"))]
    val = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2025-01-01"))
        & (df_datetime["Date"] <= pd.to_datetime("2025-04-01"))
    ]

    train_returns = train["Close"].pct_change().values[1:]
    val_returns = val["Close"].pct_change().values[1:]

    print(len(train_returns))
    print(len(val_returns))
    print()

    val_returns_total.append(val_returns)
    train_returns_total.append(train_returns)
    
train_returns_total = np.array(train_returns_total).T # shape (num_days, N = num_assets)
val_returns_total = np.array(val_returns_total).T

cov = np.cov(train_returns_total, rowvar=False)

w_opt = gradient_reduced(train_returns_total, cov)
w_rp = gradient_risk_parity(cov)

print('chosen weights optimal:', w_opt)
print('chosen weights risk parity:', w_rp)

(
    var_alpha_opt, cvar_opt, sharpe_opt, sortino_opt, cumulative_returns_opt, mean_return_opt
) = perform_validation(w_opt, val_returns_total)

(
    var_alpha_rp, cvar_rp, sharpe_rp, sortino_rp, cumulative_returns_rp, mean_return_rp
) = perform_validation(w_rp, val_returns_total)

(
    var_alpha_eqw, cvar_eqw, sharpe_eqw, sortino_eqw, cumulative_returns_eqw, mean_return_eqw
) = perform_validation(np.ones(N) / N, val_returns_total)

df = pd.DataFrame({
    "Sharpe": [sharpe_opt, sharpe_eqw, sharpe_rp],
    "Sortino": [sortino_opt, sortino_eqw, sortino_rp],
    "Var": [var_alpha_opt, var_alpha_eqw, var_alpha_rp],
    "Cvar": [cvar_opt, cvar_eqw, cvar_rp],
    "Mean return": [mean_return_opt, mean_return_eqw, mean_return_rp],
}, index=["Optimized weights", "Equal weights", "Risk parity weights"])
df

249
63

249
63

249
63

249
63

249
63

249
63

249
63

Step 0: objective = -0.003396
Step 200: objective = -0.002446
Step 400: objective = -0.002446
Step 600: objective = -0.002446
Step 800: objective = -0.002446
Step 1000: objective = -0.002446
Step 1200: objective = -0.002446
Step 1400: objective = -0.002446
Step 1600: objective = -0.002445
Step 1800: objective = -0.002446
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
chosen weights optimal: [0.17072469 0.10815918 0.1384753  0.17181906 0.14737406 0.13307038
 0.13037725]
chosen weights risk parity: [0.14288683 0.14286682 0.14288683 0.14288683 0.1428242  0.1428242
 0.1428242 ]

                       Sharpe   Sortino       Var      Cvar  Mean return
Optimized weights    0.582074  1.208277 -0.007756 -0.010640     0.000214
Equal weights        0.628597  1.289585 -0.007833 -0.010334     0.000231
Risk parity weights  0.628562  1.289514 -0.007832 -0.010334     0.000231

In [96]:
fig = go.Figure()
L = list(range(len(cumulative_returns_opt)))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_eqw, name="equal weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_rp, name="risk parity weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_opt, name="optimized weights"))
fig.show()

In [13]:

val_returns_total = []
train_returns_total = []

for df in filtered_dfs:
    df_datetime = df.copy()
    df_datetime["Date"] = pd.to_datetime(df_datetime["Date"])
    train = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2019-02-05"))
        & (df_datetime["Date"] <= pd.to_datetime("2020-02-12"))]
    val = df_datetime[
        (df_datetime["Date"] >= pd.to_datetime("2020-02-12"))
        & (df_datetime["Date"] <= pd.to_datetime("2020-04-03"))
    ]

    train_returns = train["Close"].pct_change().values[1:]
    val_returns = val["Close"].pct_change().values[1:]

    print(len(train_returns))
    print(len(val_returns))
    print()

    val_returns_total.append(val_returns)
    train_returns_total.append(train_returns)
    
train_returns_total = np.array(train_returns_total).T # shape (num_days, N = num_assets)
val_returns_total = np.array(val_returns_total).T

cov = np.cov(train_returns_total, rowvar=False)

w_opt = gradient_reduced(train_returns_total, cov)
w_rp = gradient_risk_parity(cov)

print('chosen weights optimal:', w_opt)
print('chosen weights risk parity:', w_rp)

(
    var_alpha_opt, cvar_opt, sharpe_opt, sortino_opt, cumulative_returns_opt, mean_return_opt
) = perform_validation(w_opt, val_returns_total)

(
    var_alpha_rp, cvar_rp, sharpe_rp, sortino_rp, cumulative_returns_rp, mean_return_rp
) = perform_validation(w_rp, val_returns_total)

(
    var_alpha_eqw, cvar_eqw, sharpe_eqw, sortino_eqw, cumulative_returns_eqw, mean_return_eqw
) = perform_validation(np.ones(N) / N, val_returns_total)

df = pd.DataFrame({
    "Sharpe": [sharpe_opt, sharpe_eqw, sharpe_rp],
    "Sortino": [sortino_opt, sortino_eqw, sortino_rp],
    "Var": [var_alpha_opt, var_alpha_eqw, var_alpha_rp],
    "Cvar": [cvar_opt, cvar_eqw, cvar_rp],
    "Mean return": [mean_return_opt, mean_return_eqw, mean_return_rp],
}, index=["Optimized weights", "Equal weights", "Risk parity weights"])
df

252
37

252
37

252
37

252
37

252
37

252
37

252
37

Step 0: objective = -0.003276
Step 200: objective = -0.002289
Step 400: objective = -0.002289
Step 600: objective = -0.002289
Step 800: objective = -0.002289
Step 1000: objective = -0.002289
Step 1200: objective = -0.002290
Step 1400: objective = -0.002291
Step 1600: objective = -0.002291
Step 1800: objective = -0.002291
Step 0: objective = -0.002857
Step 200: objective = -0.002857
Step 400: objective = -0.002857
Step 600: objective = -0.002857
Step 800: objective = -0.002857
Step 1000: objective = -0.002857
Step 1200: objective = -0.002857
Step 1400: objective = -0.002857
Step 1600: objective = -0.002857
Step 1800: objective = -0.002857
chosen weights optimal: [0.1651642  0.09643536 0.1311008  0.16436002 0.14088394 0.14744465
 0.15461107]
chosen weights risk parity: [0.14285715 0.14285715 0.14285715 0.14285715 0.14285715 0.14285715
 0.14285715]

                       Sharpe   Sortino       Var      Cvar  Mean return
Optimized weights   -3.573863 -7.084715 -0.038750 -0.056981    -0.006045
Equal weights       -3.476657 -7.111435 -0.038604 -0.055634    -0.005743
Risk parity weights -3.476657 -7.111435 -0.038604 -0.055634    -0.005743

In [98]:
fig = go.Figure()
L = list(range(len(cumulative_returns_opt)))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_eqw, name="equal weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_rp, name="risk parity weights"))
fig.add_trace(go.Scatter(x=L, y=cumulative_returns_opt, name="optimized weights"))
fig.show()